apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: qotd-build-and-deploy-{cuid}
  labels:
    sandbox: learn-pipelines-{cuid}
    learn-pipelines: pipeline-{cuid} 
spec: 
  workspaces: 
  - name: shared-workspace
  params: 
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/chaimach/qotd.git
  - name: IMAGE
    type: string
    description: image to be built from the code
    default: image-registry.openshift-image-registry.svc:5000/training-project/qotd:latest
  - name: BRANCH
    type: string
    description: branch of the git repo
    default: master
  tasks: 
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: branch
      value: $(params.BRANCH)
    - name: deleteExisting
      value: "true"
  - name: build-image 
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: apply-manifests-{cuid} 
    taskRef:
      name: apply-manifests-{cuid}
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter: 
    - build-image
